spring.application.name=planificador-tareas
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/planificador_tareas}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
